version: "2"

services:
  spoon_shushu_shu:
    build: .
    command: bundle exec ruby rec_spoon.rb 314949026 # @shushu_shu
    environment:
      API_URL: $API_URL
    restart: unless-stopped
    volumes:
      - $SPOON_OUTPUT_DIR:/output

  k1105:
    build: .
    command: bundle exec ruby rec_spoon.rb 315315671 # @k___.1105
    environment:
      API_URL: $API_URL
    restart: unless-stopped
    volumes:
      - $SPOON_OUTPUT_DIR:/output

  kurotan333:
    build: .
    command: bundle exec ruby rec_spoon.rb 313974384 # @kurotan333
    environment:
      API_URL: $API_URL
    restart: unless-stopped
    volumes:
      - $SPOON_OUTPUT_DIR:/output
